# coding: utf-8

"""
    Nomad Hawk

    This is the API descriptor for the Nomad Hawk API, responsible for tracking and analytics.  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: paul@samarkand.global
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.event_item import EventItem  # noqa: E501
from swagger_client.rest import ApiException


class TestEventItem(unittest.TestCase):
    """EventItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventItem(self):
        """Test EventItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.event_item.EventItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
