# coding: utf-8

"""
    Nomad Hawk

    This is the API descriptor for the Nomad Hawk API, responsible for tracking and analytics.  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: paul@samarkand.global
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.track_api import TrackApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTrackApi(unittest.TestCase):
    """TrackApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.track_api.TrackApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_track(self):
        """Test case for track

        Record an individual event  # noqa: E501
        """
        pass

    def test_track_0(self):
        """Test case for track_0

        Record an individual event  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
