variables:
  HARBOR_LONDON_REGISTRY: harbor-uk.samarkand.io

image: maven:3-jdk-7

stages:
  - build
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - modules/swagger-codegen-cli/target/
  script:
    - mvn clean package

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  dependencies:
    - build
  script:
    - cd modules/swagger-codegen-cli
    - docker login -u harborbot -p $HARBOR_REGISTRY_PASSWORD harbor-uk.samarkand.io
    - docker build -t $HARBOR_LONDON_REGISTRY/$CI_PROJECT_PATH:swagger-codegen-cli .
    - docker push $HARBOR_LONDON_REGISTRY/$CI_PROJECT_PATH:swagger-codegen-cli